### ISSUE TITLE
Transfer project to jaraco

### ISSUE THREAD

**Issue by jaraco** [jaraco/inflect#103]
Given the ~~lack of support for Azure pipelines (#101)~~, the ~~less streamlined process for releases (#80)~~, and the exclusion of sponsorship for these projects (#102), the inclusion of this project in Jazzband is now more of a hindrance than a benefit.

@jezdez Would you please transfer the project back to `/jaraco`?

**Comment by jaraco** [comment]
To be sure, I still very much appreciate the principles of Jazzband, and support its efforts and the work of Jannis to create this forum.

**Comment by jaraco** [comment]
Please let me know if you have any misgivings about this request.

**Comment by jaraco** [comment]
Lack of support for Azure is no longer a factor as I'm moving the project (and others I maintain) to Github Actions.

**Comment by jezdez** [comment]
@jaraco I've  sent you a transfer request (note: this comes from my personal namespace since GitHub doesn't allow transferring organization repos to individual users that are not organization owners, purely technical issue on GitHub's side). Good luck!

**Comment by jaraco** [comment]
The transfer request has expired. When I follow the link, I see this:

![image](https://user-images.githubusercontent.com/308610/99190240-741ff980-2733-11eb-9851-ef9914e83640.png)

I suspect there's a bug with Github where editing an issue during a transfer causes the transfer request to expire. I've e-mailed support as indicated, but I suspect they'll clarify the cause and ask us to re-initiate the transfer.

@jezdez Can you attempt the transfer again?

**Comment by jezdez** [comment]
Sorry, I don't think I can attempt it again since the transfer went through IIUC:

<img width="1370" alt="CleanShot 2020-11-15 at 17 19 56@2x" src="https://user-images.githubusercontent.com/1610/99190429-c9c1c980-2766-11eb-9233-7df940bfed05.png">

**Comment by jezdez** [comment]
I'm trying to remember, did I already send a transfer request back in February?

**Comment by jaraco** [comment]
I don't think there was a transfer request in February. I checked my e-mail history and there's nothing there, though it's possible the request was flagged as spam and I missed it.

I wonder if there's an issue with transferring a repository twice in short succession, perhaps a race condition where the initial transfer to jezdez somehow caused the second transfer to jaraco to be marked as expired.

I guess at this point the only option is to wait a day and see if the option to transfer returns or if Github support responds.

There's nothing urgent about it, so I'll just wait and see.

Thanks again for your help.

**Comment by hugovk** [comment]
The repo is showing as `https://github.com/jaraco/inflect/` for me, so I guess it's just caching, and waiting a day is a good idea.

**Comment by jaraco** [comment]
Oh, indeed. I missed that in Jannis' screenshot. Glad to see it's done!

**Comment by jezdez** [comment]
No problem Jason, yeah, this smells like a race condition or cache invalidation issue on GitHub's side.

Glad this worked out nevertheless!
