### ISSUE TITLE
symbol to name

### ISSUE THREAD

**Issue by ldmtwo** [jaraco/inflect#111]
It would be great if you could support symbol to name conversion and reverse. 
Ex:

```
+ --> plus
… --> ellipsis
```

There is a bug maybe?
ie.

```
>>> number_to_words('+')
'plus zero'
```

ie.

```
>>> number_to_words('…')
'zero'
```

ie.

```
>>> number_to_words('5x5 5 x 5')
'five thousand, five hundred and fifty-five',
>>> number_to_words('5x5')
'fifty-five' 
>>> number_to_words('5 x 5')
'fifty-five'
```

**Comment by jaraco** [comment]
As I look at this again, I'm disinclined to accept the proposal, as I don't share the expectation that OP has. I _might_ expect `+` to translate to "plus", but I don't see how an ellipsis maps to zero or how "5x5" is not "five by five" or "twenty-five". It definitely doesn't look like "fifty-five" to me.

Feel free to elaborate, to explain under what circumstances the proposed behaviors would be useful. Without a compelling use-case, however, I don't see this proposal having any merit, so I'm closing for now (but willing to re-open if appropriate).
