### ISSUE TITLE
Plural of "cash"

### ISSUE THREAD

**Issue by riccardobucco** [jaraco/inflect#113]
When I use `plural_noun("cash")` the expected result is "cash" (the name might sometimes be countable, but most of the times is uncountable). However, at the moment the output is "cashes". Is it possible to solve this issue?

**Comment by riccardobucco** [comment]
Any updates?

**Comment by The-Archemist** [comment]
p.defnoun("cash", "cash")

**Comment by riccardobucco** [comment]
> p.defnoun("cash", "cash")

Shouldn't this be the default behaviour? Is it possible to set it at a library level?

**Comment by jaraco** [comment]
Agreed. Would you consider sending a PR to fix the issue?
