### ISSUE TITLE
How do you check whether a word is singular or plural?

### ISSUE THREAD

**Issue by Pikamander2** [jaraco/inflect#120]
I might be missing something in the documentation, but I don't see how to check whether a word is singular or plural.

I see that you can compare two words and it'll identify each of them as being singular and plural. For example:

    inflect_engine.compare_nouns('cat', 'cats') #Returns 's:p'

But what about just a single word? I would expect there to be a function like this:

    inflect_engine.check_noun('cat') #Returns 's'

Is there a function for that?

**Comment by jaraco** [comment]
I don't have an answer to that, so I recommend you go to the source for the answer. When you find it, would you report back here? If it's a feature that doesn't exist, consider implementing it. Thanks!

**Comment by jaraco** [comment]
I've seen other issues that discuss that for some operations, one can check of the result `is False`. Unfortunately, I can't find the comment I saw only minutes ago because Github won't search for that phrase (it will, but it ignores the quotes on `"is False"`).

I don't have a better answer.
