### ISSUE TITLE
Plural issues?

### ISSUE THREAD

**Issue by mbr** [jaraco/inflect#15]
Some are wrong, I _think_:

```
>>> p.plural('corpus')  # corpora
'corpuses'
>>> p.plural('means')  # means
'mean'
>>> p.plural('vita')   # vitae
'vitas'
>>> p.plural('backhoe')
'backhoes'
>>> p.plural('hoe')  # hoes
'ho'
>>> p.plural('ho')   # hos
'h'
```

These are technically correct, but unusual (and not a mistake like the octupus-plural):

```
>>> p.plural('radius')  # radii, radiuses
'radiuses'
>>> p.plural('curriculum')  # curricula, curriculums
'curriculums'
>>> p.plural('medium')  # mediums, media
'mediums'
>>> p.plural('appendix')  # appendixes, appendices
'appendixes'
# also index
```

Not sure how it should work for uncountables:

```
>>> p.plural('cattle')  # cattle        
'cattles'
```

**Comment by duhaime** [comment]
Strictly for the curious, it's worth noting that there are stranger pluralizations:

<pre><code>>>> word = 'dogs'
>>> print(p.inflect("The plural of {0} is plural({0})".format(word)))
The plural of dogs is dog
>>> word = 'cats'
>>> print(p.inflect("The plural of {0} is plural({0})".format(word)))
The plural of cats is cat
>>> word = 'ponies'
>>> print(p.inflect("The plural of {0} is plural({0})".format(word)))
The plural of ponies is pony
</code></pre>

**Comment by pwdyson** [comment]
Two points. Firstly, if you put garbage in you get garbage out.

Secondly, this library gives the plurals of verbs as well as nouns, so these are actually correct as they are verb plurals.

The plural of "walks" is "walk" because the singular is "Andy walks" and the plural is "They walk".

The creditor dogs Andy until Andy pays the bill.
The creditors dog Andy until Andy pay the bill.

Andy ponies up to Charlie.
They pony up to Charlie.

"to cat" means to search for a sexual mate.

Of course, you can find a noun that is not also a verb and then garbage in garbage out applies.

**Comment by duhaime** [comment]
Thanks so much Paul, this helps. 

I have a quick question: If one wishes to determine whether a given noun is singular or plural, is there a reasonably straightforward way to try and do so with inflect? I have large lists of nouns like "soldiers", "players", "knights", "king", and wish to determine the count of each. Any tips you can offer would be greatly appreciated.

**Comment by pydsigner** [comment]
@duhaime, p.singular_noun() returns False if the noun is already singular.

For instance:
```
>>> p.singular_noun('horses')
'horse'
>>> p.singular_noun('horse')
False
>>> p.singular_noun('knights')
'knight'
>>> p.singular_noun('knight')
False
>>> p.singular_noun('soldier')
False
```
So a plural can be written like so:
```python
def is_plural(engine, noun):
    return engine.singular_noun(noun) is not False
```

Example usage:
```
>>> is_plural(p, 'soldier')
False
>>> is_plural(p, 'soldiers')
True
```

**Comment by AndrewGnagy** [comment]
This is a bit specific, but:
```
>>> p.singular_noun("status")
'statu'
```
I was expecting this to return False.

**Comment by virresh** [comment]
Just another one to the list
```python
>>> engine.singular_noun('boss')
'bos'
```
I expected `False`.

**Comment by Bipulkumarsingh** [comment]
Words with 'Y' need to convert into 'ies'.
CATEGORY  <--->  CATEGORYS,    Expected --> CATEGORIES

**Comment by jaraco** [comment]
> This is a bit specific, but:
> 
> ```
> >>> p.singular_noun("status")
> 'statu'
> ```
> 
> I was expecting this to return False.

Except the plural of 'status' is 'status'. This issue has been subsequently fixed. Thanks pydsigner for the description. I've used your examples to expand the doctests to describe that intended behavior.

In #76, the user reports some other words that behave poorly under `singular_noun`:

```
'pancreas', 'mitosis', 'sepsis', 'assess', 'access', 'status', 'photolysis', 'actress'
```

**Comment by jaraco** [comment]
In #46, the user also reports that `singular_noun` on words ending in `ss` do not return False when singular:

`dress, address, wellness, fitness, clothes, boss, class, glass`

And there, pwdyson contradicts pydsigner's statement:

> p.singular_noun() returns False if the noun is already singular.

with:

> If you ask for the singular of something that is not already a plural the output will not be sensible.

Probably this behavior should be made official. For now, the change in 560b6f9 is the official stance, but we may have to relax that intention.

**Comment by hugovk** [comment]
> Except the plural of 'status' is 'status'. This issue has been subsequently fixed.

This surprises me, I thought the plural was 'statuses'. Is plural 'status' an American English thing? Please could you give an example? 

Merriam-Webster says:

> sta·​tus | \ ˈstā-təs  , ˈsta-  \
plural statuses

https://www.merriam-webster.com/dictionary/status

The OED says:

> Inflections:   Plural (rare) status /ˈsteɪtjuːs/, (now usu.) statuses /ˈsteɪtəsɪz/, (rare) statusses /ˈsteɪtəsɪz/.

**Comment by jaraco** [comment]
I'm almost certainly mistaken about `status`.

**Comment by jaraco** [comment]
I'm not sure what to do about this issue. It feels a little diffuse and has lingered for a long time. I welcome a renewed effort to address it, and I'd suggest to start by opening a new issue that summarizes and consolidates the essential problem based on the investigation above.
