### ISSUE TITLE
inflect/__init__.py::inflect.engine.compare test fails with pydantic-core >= 2.12

### ISSUE THREAD

**Issue by jhatler** [jaraco/inflect#204]
The below PR on pydantic-core introduced a change to the validation error messages which breaks the inflect/__init__.py::inflect.engine.compare test.

https://github.com/pydantic/pydantic-core/pull/1050

The test breaks because the error message defined at the below line is plural when the number "1" is used, which is grammatically incorrect.

https://github.com/jaraco/inflect/blob/eff29a4177d5c5dedf88617b7c60d7a6679c440e/inflect/__init__.py#L2469

**Comment by jaraco** [comment]
Thanks for the report and the pull request. I addressed the issue in 5ef0baba20bb7c6ebd9b6cb0bda73ba0873fef9f.
