### ISSUE TITLE
more-itertools dependency needs to be at least v8.5

### ISSUE THREAD

**Issue by mertuygr** [jaraco/inflect#215]
more-itertools dependency should be at least v8.5 since `windowed_complete` function is added in v8.5
https://github.com/more-itertools/more-itertools/blob/master/docs/versions.rst#850
https://github.com/jaraco/inflect/blob/1f42293f30caacb0637f7eb30a483b44489f4812/inflect/__init__.py#L3008

**Comment by jaraco** [comment]
While technically correct, v8.5 was released almost four years ago. In my experience, a lower bound is mainly useful in the first few months of a feature's release, as installers pick up the latest version by default and only environments still stuck with old cruft are exposed to the older behavior.

How did you come across this issue? Did it affect you? If so, I'd like to know how so I can update my understanding of the situations affected by unbounded dependencies. Did you run a tool to detect what the bound should be, and if so, which one?

**Comment by mertuygr** [comment]
I have a direct dependency to on an older version of the more-itertools in my codebase, and I am using [poetry](https://github.com/python-poetry/poetry) to manage dependencies. In my case since we are shipping an application not an library the dependencies are locked using a lock file to increase stability of the application. When I add inflect to my pyproject.toml. Poetry thinks the more-itertools dependency of the inflect is already satisfied while resolving dependencies and gives me the green light since no lower bounds are set in its dependency list. However I was welcomed with `windowed_complete` function was missing when I run the `import inflect`.

As fas I know there is no tool to detect minimum lower cap for dependencies. One way I would approach this would be setting a lower cap to show possible conflicts for the library users' codebase dependencies. They will take advantage of the latest version of the dependency anyway as long as there is no upper cap. On the other hand not setting any caps hides the requirement from the package managers. I am not subject of expert on this one though it is just my 2 cents.

**Comment by jaraco** [comment]
Thanks for the explanation. That makes sense. We once considered adopting lockfiles in workflows at companies where I've worked and I was resistant to them for that reason (stable but stale by default). But I understand the motivations. Let's add the bound.
