### ISSUE TITLE
Improving the formatting of the README, particularly the giant code block under SYNOPSIS

### ISSUE THREAD

**Issue by joshstephenson** [jaraco/inflect#219]
The giant code block under SYNOPSIS could be improved by breaking it into separate code blocks with interwoven markdown more like the FORMING PLURALS AND SINGULARS section. I also believe the formatting of the description could be improved.

Please let me know if you would be interested in this and I will submit a PR.

**Comment by jaraco** [comment]
Sounds good to me. Thanks.
