### ISSUE TITLE
anything ending with ss comes out with one s with singular_noun

### ISSUE THREAD

**Issue by simudream** [jaraco/inflect#46]
p = inflect.engine()
p.singular_noun('dress')
'dres'
p.singular_noun('address')
'addres'

**Comment by anyeone** [comment]
I also see this with "ness" words such as p.singular_noun("wellness") = "welnes" and p.singular_noun("fitness") = "fitnes"

It also turned "clothes" into "clothe"

**Comment by pwdyson** [comment]
This is intended behaviour as this module is garbage in garbage out. If you ask for the singular of something that is not already a plural the output will not be sensible.

**Comment by jwg4** [comment]
I don't agree that this is intended behavior. If you ask for the singular of 'foo' it returns `False` as it recognizes that no plural is of this form. If you ask for the singular of a word ending in 'ss' it should also return False, as no plural of a word ending in 's' is formed by adding an additional 's'.

**Comment by jcollard** [comment]
Also experiencing this issue.

**Comment by virresh** [comment]
Just another one to the list
```python
>>> engine.singular_noun('boss')
'bos'
>>> engine.singular_noun('class')
'clas'
>>> engine.singular_noun('glass')
'glas'
```
`False` would be more appropriate.

**Comment by jaraco** [comment]
I've added these words as examples to consider in #15.
