### ISSUE TITLE
plural on plural words returns singular

### ISSUE THREAD

**Issue by AniSkywalker** [jaraco/inflect#94]
if plural() is called on a plural word, it returns singular form. 

p.plural('pastas')
'pasta'

Should it not return False like singular_noun?

**Comment by jaraco** [comment]
> Should it not return False like singular_noun?

Not necessarily. In fact, there's nothing in the docs or code that suggests that `plural` ever returns `False`.

Also, `plural` is known to be used on verbs, which can have the (sometimes) surprising but accurate behavior of appearing to make a plural singular (see https://github.com/jaraco/inflect/issues/15#issuecomment-109791934).

When you ask for the plural of something that's already plural, the outcome is undefined.

If you think the behavior could be enhanced, please feel free to describe the use-case that you're trying to solve (i.e. why are you trying to pluralize an already plural noun) and be prepared to produce a design to address it.
