### ISSUE TITLE
Adding variable case transformations to this project.

### ISSUE THREAD

**Issue by gregschmit** [jaraco/inflect#97]
Hi all,

I found this project while considering creating a fork of the `inflection` package, as the current one seems to be [abandoned](https://github.com/jpvanhal/inflection/issues/39). This package mostly does what that package does, however AFAICT, this package does not do transformations to/from camelCase, underscore_case, or PascalCase. I totally understand that it's a good idea to prevent feature creep in a project, so I'm opening this issue to ask the community here if you all think that adding such features (which seem to be fairly easy to implement) would be a good idea? Mainly I'm asking because I have a project which used `inflection` but couldn't use `inflect` in its current state.

To prevent polluting your existing namespace, we could even have a submodule called `var` which handles these transformations, named such because they are almost always variable/class names (or URL segments that translate to variables/classes). In case you're not clear on how those methods might work, here are some examples:

    import inflect

    p = inflect.engine()
    p.var.underscore_to_camel("test_string")  # "testString"
    p.var.underscore_to_pascal("test_string")  # "TestString"
    p.var.pascal_to_underscore("TestString")  # "test_string"
    p.var.pascal_to_underscore("TestString", pluralize=True)  # "test_strings"
    p.var.pluralize("test_string")  # "test_strings"

So what say you? Do you think adding variable case methods would be a good idea? I'm open to ideas about how it's actually implemented, but I would be happy to create a working implementation, but I figured I would ask this community first if you would consider expanding the scope of this project.

If not, my other idea was to create a new package that has this library as a dependency which handles this stuff. Let me know your thoughts.

**Comment by hugovk** [comment]
Sounds like a useful addition to inflect.py. I've no strong opinion on whether to add it in a `var` submodule or not. Thanks!

**Comment by jaraco** [comment]
I'm also positive about this proposition.

I've personally implemented this behavior in [jaraco.text.WordSet](https://jaracotext.readthedocs.io/en/latest/#jaraco.text.WordSet). One nice feature about `WordSet` is that it doesn't require the input to be pre-analyzed. It infers the word boundaries automatically.

I'm open to a proposal, especially if the integration is intuitive. If the functionality is implemented in inflect, I'd like to see it supersede and obviate the behavior in `jaraco.text`.

**Comment by jaraco** [comment]
For now, I'm going to add a reference to WordSet in the documentation. If someone wishes to see this behavior consolidated in `inflect`, I welcome a design proposal, but the separation of concerns provided by the status quo seems perfectly acceptable.
